"""empty message

Revision ID: 4a16ac4630c5
Revises: 
Create Date: 2016-11-28 14:06:34.111575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a16ac4630c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=0),
    sa.Column('text', sa.String(), nullable=0),
    sa.Column('info', sa.String(), nullable=0),
    sa.Column('auth', sa.String(), nullable=1),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('text')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=0),
    sa.Column('cover', sa.String(), nullable=0),
    sa.Column('digest', sa.String(), nullable=0),
    sa.Column('content', sa.String(), nullable=0),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content'),
    sa.UniqueConstraint('cover'),
    sa.UniqueConstraint('digest'),
    sa.UniqueConstraint('title')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=0),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    op.drop_table('articles')
    op.drop_table('accounts')
    ### end Alembic commands ###
